
record Person(String name, int age) {
  Person(String name, int age) { // Noncompliant, already autogenerated
    this.name = name;
    this.age = age;
  }
}

record Person(String name, int age) {
  Person { // Noncompliant, no need for empty compact constructor
  }
  public String name() { // Noncompliant, already autogenerated
    return name;
  }
}
